version: '3.5'

services:
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    hostname: 'Aliyun-01' # 所在节点的hostname
    ports:
      - "9100:9100"
    restart: always
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'