# Prometheus全局配置项
global:
  scrape_interval: 15s # 默认抓取周期，可用单位ms、smhdwy #设置每15s采集数据一次，默认1分钟
  evaluation_interval: 15s # 估算规则的默认周期 # 每15秒计算一次规则。默认1分钟

rule_files:
  - "./rules/*.yml"

# 告警配置
alerting:
  alertmanagers:
    - static_configs:
        - targets: [ 'xx.xx.xx.xx:9093' ]

# 配置抓取
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'localhost:9090' ]
        labels:
          appname: 'prometheus'
  - job_name: 'agent'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'xx.xx.xx.xx:9100', 'xx.xx.xx.xx:9100','xx.xx.xx.xx:9100' ]
  - job_name: 'mysql'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'xx.xx.xx.xx:9104','xx.xx.xx.xx:9104' ]
